# Generated by Django 6.1 on 2026-08-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_message_id', models.BigIntegerField()),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('text', models.TextField()),
                ('message_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('ERROR', 'Error'), ('IGNORED', 'Ignored')], default='PROCESSED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('telegram_chat_id', 'telegram_message_id'), name='uniq_telegram_chat_message')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('NOTIFIED', 'Notified'), ('RESOLVED', 'Resolved')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='processing_error', to='core.telegrammessage')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activity_type', models.CharField(choices=[('DEF', 'DEF'), ('FARM', 'FARM')], max_length=8)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.player')),
                ('telegram_message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='core.telegrammessage')),
            ],
        ),
    ]
