# Generated by Django 6.1 on 2026-08-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_default_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
