# Generated by Django 6.1 on 2026-08-13 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_telegram_user_id_player_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.player'),
        ),
    ]
