# Generated by Django 6.1 on 2026-08-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_instruction_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='telegram_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.telegrammessage'),
        ),
    ]
