# Generated by Django 6.1 on 2026-08-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_instruction_wave_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
