# Generated by Django 6.1 on 2026-08-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='telegram_user_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='telegram_username',
        ),
    ]
