# Generated by Django 6.1 on 2026-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_player_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('rate_kk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='has_cast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('DEF', 'DEF'), ('FARM', 'FARM'), ('CAST', 'CAST')], max_length=8),
        ),
    ]
