# Generated by Django 6.1 on 2026-08-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_update_instruction_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_user_id__isnull', False)), fields=('telegram_user_id',), name='uniq_player_telegram_user_id'),
        ),
    ]
