# Generated by Django 6.1 on 2026-08-22 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_update_instruction_single_nick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_chat_id', models.BigIntegerField()),
                ('source_message_id', models.BigIntegerField()),
                ('target_chat_id', models.BigIntegerField()),
                ('target_message_id', models.BigIntegerField()),
                ('alliance_bot_username', models.CharField(blank=True, default='', max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('last_text', models.TextField(default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_mirrors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
