# Generated by Django 6.1 on 2026-08-22 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_schedulemirror'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedulemirror',
            constraint=models.UniqueConstraint(fields=('source_chat_id', 'source_message_id'), name='uniq_schedule_mirror_source'),
        ),
    ]
