# Generated by Django 6.1 on 2026-08-25 15:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_registration_rate(apps, schema_editor):
    RegistrationRate = apps.get_model("core", "RegistrationRate")
    RegistrationRate.objects.get_or_create(
        start_time="00:00",
        end_time="23:59",
        defaults={"rate_kk": Decimal("10.00"), "active": True, "order": 0},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_schedulemirror_uniq_schedule_mirror_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('rate_kk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тариф за регистрацию',
                'verbose_name_plural': 'Тарифы за регистрацию',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clans_count', models.PositiveIntegerField()),
                ('payment_kk', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('photo_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.player')),
                ('telegram_message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='core.telegrammessage')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.RunPython(seed_registration_rate, migrations.RunPython.noop),
    ]
