# Generated by Django 6.1 on 2026-08-25 16:07

from django.db import migrations
from django.db.models import Q


INSTRUCTION_CONTENT = """Запись активности на форте

Отправляй сообщение ТОЛЬКО за себя. Формат:

+время на волне | тип | ник | время начала волны | описание

Поля:
1. Время — сколько часов: 1, 2, 0,5 (через запятую) или 0.5 (через точку).
2. Тип — деф (оплачивается), фарм (учитывается, но не оплачивается) или каст. Можно комбинировать: деф+каст. Регистр не важен.
3. Ник — ТВОЙ ник, один, только буквы (рус/англ) и цифры. Не пиши за других и не указывай несколько ников.
4. Время начала волны — ОБЯЗАТЕЛЬНО. Формат HH.MM или HH:MM (например, 11.56 или 11:56).
5. Описание — любой текст (волна, замок, комментарий). Необязательно.

Пример: +1 | деф+каст | Swettka | 11.56 | Деф и каст

Если допустил ошибку — отредактируй своё сообщение по шаблону.

## Регистрация клана на атаку форта

Формат сообщения (обязательно прикрепляй скриншот):
Рега N кланами [описание]
Регистрация N кланов [описание]

Поля:
1. Ключевое слово — «рега» или «регистрация» (в начале сообщения, регистр не важен).
2. Число кланов — целое положительное число (1, 2, 3...).
3. Описание — любой текст (например, цель атаки). Необязательно.

Пример: Рега 2 кланами — атака форта

Оплата: число кланов × тариф за регистрацию (см. «Тарифы за регистрацию» в настройках).
Скриншот обязателен — без него регистрация не принимается к оплате.
"""

previous_content = {}


def update_instruction_content(apps, schema_editor):
    Instruction = apps.get_model("core", "Instruction")
    global previous_content
    previous_content = dict(
        Instruction.objects.filter(
            Q(slug="how-to-write-activity") | Q(title="Запись активности на форте")
        ).values_list("pk", "content")
    )
    Instruction.objects.filter(
        Q(slug="how-to-write-activity") | Q(title="Запись активности на форте")
    ).update(content=INSTRUCTION_CONTENT)


def revert_instruction_content(apps, schema_editor):
    Instruction = apps.get_model("core", "Instruction")
    if not previous_content:
        return
    for pk, content in previous_content.items():
        Instruction.objects.filter(pk=pk).update(content=content)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_registration_models'),
    ]

    operations = [
        migrations.RunPython(update_instruction_content, revert_instruction_content),
    ]
