# Generated by Django 6.1 on 2026-08-29 12:06
# Manual edit: keep only the activity-edit-corrections fields.
# Pre-existing ScheduleMirror metadata drift (verbose_name/help_text) is NOT
# included here because it is unrelated to this task; see Architect report.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_create_members_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Время последнего редактирования', null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество редактирований'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='edit_history',
            field=models.JSONField(blank=True, default=list, help_text='Цепочка предыдущих текстов сообщения'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='original_text',
            field=models.TextField(blank=True, default='', help_text='Оригинальный текст до первого редактирования'),
        ),
    ]
