# Generated by Django 6.1 on 2026-08-30 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_backfill_original_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulemirror',
            options={'ordering': ['-created_at'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='alliance_bot_username',
            field=models.CharField(blank=True, default='', help_text='Без @, например: x5_fort_bot.', max_length=64, verbose_name='Username бота альянса'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_mirrors', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Необязательная метка для удобства (например: «Расписание на неделю»).', max_length=255, verbose_name='Название / метка'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='last_text',
            field=models.TextField(default='', verbose_name='Последний текст расписания'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='source_chat_id',
            field=models.BigIntegerField(help_text='Группа/канал, где бот альянса публикует расписание.', verbose_name='ID исходного чата (мостовая группа)'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='source_message_id',
            field=models.BigIntegerField(help_text='ID сообщения от бота альянса (узнать через @getidsbot или в логах).', verbose_name='ID сообщения с расписанием'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='target_chat_id',
            field=models.BigIntegerField(help_text='Группа клана, куда зеркалируется расписание.', verbose_name='ID целевого чата (группа клана)'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='target_message_id',
            field=models.BigIntegerField(help_text='Сообщение, которое бот обновляет при синхронизации.', verbose_name='ID сообщения в целевой группе'),
        ),
        migrations.AlterField(
            model_name='schedulemirror',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
