# Generated by Django 6.1 on 2026-08-31 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_schedulemirror_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='message_thread_id',
            field=models.BigIntegerField(blank=True, help_text='message_thread_id форумной темы, из которой пришло сообщение (если есть).', null=True, verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='ID чата')),
                ('telegram_message_id', models.BigIntegerField(help_text='ID, присвоенный Telegram при отправке.', verbose_name='ID сообщения в Telegram')),
                ('text', models.TextField(verbose_name='Текст')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('reply_to_message_id', models.BigIntegerField(blank=True, help_text='ID сообщения, на которое дан ответ (reply).', null=True, verbose_name='ID исходного сообщения')),
                ('reply_to_text', models.TextField(blank=True, default='', verbose_name='Текст исходного сообщения')),
                ('topic_name', models.CharField(blank=True, default='', help_text='Название темы, в которую отправлено сообщение (для аудита).', max_length=255, verbose_name='Тема')),
                ('status', models.CharField(choices=[('SENT', 'Отправлено'), ('ERROR', 'Ошибка')], default='SENT', max_length=16, verbose_name='Статус')),
                ('error_text', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправил')),
            ],
            options={
                'verbose_name': 'Исходящее сообщение',
                'verbose_name_plural': 'Исходящие сообщения',
                'ordering': ['-created_at'],
            },
        ),
    ]
