# Generated by Django 6.1 on 2026-08-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_telegrammessage_message_thread_id_outgoingmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='status',
            field=models.CharField(choices=[('SENT', 'Отправлено'), ('ERROR', 'Ошибка'), ('PENDING', 'В очереди')], default='SENT', max_length=16, verbose_name='Статус'),
        ),
    ]
