# Generated by Django 6.1 on 2026-09-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_outgoingmessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_chat_id', models.BigIntegerField(blank=True, help_text='Числовой ID группы Telegram (например, -1001234567890), в которую отправляются новые сообщения из веб-интерфейса.', null=True, verbose_name='ID группы для новых сообщений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка группы',
                'verbose_name_plural': 'Настройки группы',
            },
        ),
        migrations.CreateModel(
            name='TelegramTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название темы')),
                ('thread_id', models.BigIntegerField(unique=True, verbose_name='ID темы в Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Форумная тема',
                'verbose_name_plural': 'Форумные темы',
                'ordering': ['name'],
            },
        ),
    ]
