# Generated by Django 6.1 on 2026-09-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_telegramsettings_telegramtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramtopic',
            options={'ordering': ['name'], 'verbose_name': 'Телеграм-тема', 'verbose_name_plural': 'Телеграм-темы'},
        ),
    ]
