# Generated by Django 6.1 on 2026-09-02

from django.db import migrations, models
import django.db.models.deletion


def backfill_groups(apps, schema_editor):
    """Превращает единственную настройку группы в «активную группу» и
    привязывает существующие темы к группе.

    - Если уже есть активная группа — используем её.
    - Иначе, если есть существующая настройка группы — делаем её активной.
    - Иначе, если есть темы без группы — создаём активную группу и привязываем.
    - Если данных нет (пустая БД) — ничего не делаем.
    """
    TelegramSettings = apps.get_model("core", "TelegramSettings")
    TelegramTopic = apps.get_model("core", "TelegramTopic")

    group = TelegramSettings.objects.filter(is_active=True).first()
    if group is not None:
        return

    existing = TelegramSettings.objects.order_by("id").first()
    if existing is not None:
        group = existing
        group.is_active = True
        group.name = group.name or "Основная группа"
        group.save(update_fields=["is_active", "name"])
    else:
        if TelegramTopic.objects.exists():
            group = TelegramSettings.objects.create(
                name="Основная группа",
                is_active=True,
            )
        else:
            return

    TelegramTopic.objects.update(group=group)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_telegramtopic_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramsettings",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активная группа"),
        ),
        migrations.AddField(
            model_name="telegramsettings",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="Название группы"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telegramtopic",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="core.telegramsettings",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="telegramtopic",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название темы"),
        ),
        migrations.AlterField(
            model_name="telegramtopic",
            name="thread_id",
            field=models.BigIntegerField(verbose_name="ID темы в Telegram"),
        ),
        migrations.RunPython(backfill_groups, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="telegramtopic",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="core.telegramsettings",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="telegramsettings",
            name="group_chat_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Числовой ID группы Telegram (например, -1001234567890), в которую отправляются новые сообщения из веб-интерфейса.",
                null=True,
                unique=True,
                verbose_name="ID группы в Telegram",
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramsettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="uniq_active_telegram_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramtopic",
            constraint=models.UniqueConstraint(
                fields=("group", "name"),
                name="uniq_topic_name_per_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramtopic",
            constraint=models.UniqueConstraint(
                fields=("group", "thread_id"),
                name="uniq_topic_thread_per_group",
            ),
        ),
        migrations.AlterModelOptions(
            name="telegramsettings",
            options={
                "ordering": ["name"],
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
    ]
