# Generated by Django 6.1 on 2026-09-03 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_telegramsettings_group_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='source',
            field=models.CharField(choices=[('manual_reply', 'Ручной ответ'), ('manual_new', 'Ручное сообщение'), ('scheduled', 'Автоматическое')], default='manual_new', max_length=16, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправил'),
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('weekdays', models.JSONField(default=list, help_text='Номера дней недели, 0=Пн ... 6=Вс', verbose_name='Дни недели')),
                ('time', models.TimeField(verbose_name='Время (MSK)')),
                ('frequency', models.CharField(choices=[('weekly', 'Каждую неделю'), ('biweekly', 'Раз в 2 недели'), ('monthly', 'Ежемесячно'), ('custom_dates', 'Произвольные даты')], default='weekly', max_length=16, verbose_name='Частота')),
                ('start_date', models.DateField(help_text="Первое срабатывание; для 'раз в 2 недели' от неё отсчёт +14 дней", verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('custom_dates', models.JSONField(blank=True, default=list, help_text='Список дат в формате YYYY-MM-DD', verbose_name='Конкретные даты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.telegramtopic', verbose_name='Тема в Telegram')),
            ],
            options={
                'verbose_name': 'Автоматическое сообщение',
                'verbose_name_plural': 'Автоматические сообщения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='scheduled_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scheduledmessage', verbose_name='Расписание'),
        ),
    ]
