# Generated by Django 6.1 on 2026-09-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_outgoingmessage_source_alter_outgoingmessage_sent_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('ERROR', 'Error'), ('IGNORED', 'Ignored'), ('REGULAR', 'Обычное')], default='PROCESSED', max_length=16),
        ),
    ]
