# Generated by Django 6.1 on 2026-09-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_scheduledmessage_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledmessage',
            options={'ordering': ['name'], 'verbose_name': 'Сообщение по расписанию', 'verbose_name_plural': 'Сообщения по расписанию'},
        ),
    ]
