# Generated by Django 6.1 on 2026-09-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_scheduledmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField(blank=True, default='', help_text='Пустой текст — приветствия выключены.', verbose_name='Текст приветствия')),
                ('block_until', models.DateTimeField(blank=True, help_text='Время окончания паузы после массового захода.', null=True, verbose_name='Блокировка приветствий до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка приветствия',
                'verbose_name_plural': 'Настройки приветствия',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('nickname__isnull', False)), fields=('nickname',), name='uniq_player_nickname_nonnull'),
        ),
    ]
