# Generated by Django 6.1 on 2026-09-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_welcomesettings_player_telegram_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='source',
            field=models.CharField(choices=[('manual_reply', 'Ручной ответ'), ('manual_new', 'Ручное сообщение'), ('scheduled', 'Автоматическое'), ('welcome', 'Приветствие')], default='manual_new', max_length=16, verbose_name='Тип'),
        ),
    ]
