# Generated by Django 6.1 on 2026-09-18 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_outgoingmessage_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossRespawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=100, unique=True, verbose_name='Название босса')),
                ('boss_type', models.CharField(choices=[('EPIC', 'Эпик РБ'), ('SUBCLASS', 'Сабкласс РБ')], max_length=16, verbose_name='Тип босса')),
                ('respawn_start', models.DateTimeField(verbose_name='Начало респа (UTC)')),
                ('respawn_end', models.DateTimeField(verbose_name='Конец респа (UTC)')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='Локация')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные (JSON)')),
                ('is_parsed_successfully', models.BooleanField(default=True, verbose_name='Успешно распарсен')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка парсинга')),
            ],
            options={
                'verbose_name': 'Респ РБ',
                'verbose_name_plural': 'Респы РБ',
                'ordering': ['respawn_start'],
            },
        ),
        migrations.CreateModel(
            name='BossRespawnSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний успех')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя ошибка')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Текст последней ошибки')),
            ],
            options={
                'verbose_name': 'Статус синхронизации респов РБ',
                'verbose_name_plural': 'Статус синхронизации респов РБ',
            },
        ),
        migrations.CreateModel(
            name='EpicBossNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_date', models.DateField(unique=True, verbose_name='Дата уведомления')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('bosses', models.JSONField(default=list, verbose_name='Боссы')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно')),
            ],
            options={
                'verbose_name': 'Журнал уведомлений Эпик РБ',
                'verbose_name_plural': 'Журналы уведомлений Эпик РБ',
                'ordering': ['-notify_date'],
            },
        ),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='source',
            field=models.CharField(choices=[('manual_reply', 'Ручной ответ'), ('manual_new', 'Ручное сообщение'), ('scheduled', 'Автоматическое'), ('welcome', 'Приветствие'), ('epic_boss', 'Эпик РБ')], default='manual_new', max_length=16, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='EpicBossNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Уведомления включены')),
                ('notification_time', models.TimeField(default='18:00', verbose_name='Время отправки')),
                ('text_template', models.TextField(blank=True, default='', help_text='Переменные: {epic_bosses} — список боссов, {url} — ссылка на страницу.', verbose_name='Шаблон текста')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.telegramtopic', verbose_name='Тема в Telegram')),
            ],
            options={
                'verbose_name': 'Настройка уведомлений Эпик РБ',
                'verbose_name_plural': 'Настройки уведомлений Эпик РБ',
            },
        ),
    ]
