# Generated by Django 6.1 on 2026-09-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_bossrespawn_bossrespawnsyncstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicbossnotificationsettings',
            name='selected_bosses',
            field=models.JSONField(blank=True, default=list, help_text='Имена боссов, по которым отправляются уведомления', verbose_name='Боссы для уведомлений'),
        ),
        migrations.AlterField(
            model_name='epicbossnotificationsettings',
            name='text_template',
            field=models.TextField(blank=True, default='🎮 Сегодня респ Эпик РБ\n\nБоссы:\n{bosses}\n\nОкно респа: ~24 часа.', help_text='Переменная {bosses} — список выбранных боссов с временем респа.', verbose_name='Шаблон текста'),
        ),
    ]
