# Generated by Django 6.1 on 2026-09-23 18:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_epic_boss_selected_bosses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonerBonusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Надбавка включена')),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Процент за 1 суммонера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Надбавка за суммонеров',
                'verbose_name_plural': 'Надбавка за суммонеров',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='summoner_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество суммонеров'),
        ),
    ]
