# Generated by Django 6.1 on 2026-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_summonerbonussettings_player_summoner_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonerbonussettings',
            name='enabled_at',
            field=models.DateTimeField(blank=True, help_text='Надбавка применяется только к активностям с датой >= этой дате. Не меняйте вручную без необходимости.', null=True, verbose_name='Дата включения'),
        ),
    ]
