# Generated by Django 6.1 on 2026-09-28 18:40

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models


def backfill_bonus_kk(apps, schema_editor):
    """Проставить bonus_kk существующим активностям по правилам надбавки.

    Логика calculate_bonus продублирована здесь (payment_kk * summoner_count *
    percent / 100, quantize 0.01, ROUND_HALF_UP), чтобы миграция не зависела
    от текущего кода сервиса.
    """
    Activity = apps.get_model("core", "Activity")
    SummonerBonusSettings = apps.get_model("core", "SummonerBonusSettings")

    try:
        settings = SummonerBonusSettings.objects.get(pk=1)
    except SummonerBonusSettings.DoesNotExist:
        return

    if not settings.is_enabled:
        return

    percent = settings.percent
    enabled_at = settings.enabled_at

    qs = Activity.objects.filter(
        activity_type="DEF",
        payment_kk__isnull=False,
    ).select_related("player")
    if enabled_at is not None:
        qs = qs.filter(created_at__gte=enabled_at)

    for activity in qs.iterator():
        payment = activity.payment_kk or Decimal("0")
        count = activity.player.summoner_count or 0
        if count <= 0 or percent <= 0 or payment <= 0:
            continue
        bonus = payment * count * percent / Decimal("100")
        activity.bonus_kk = bonus.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        activity.save(update_fields=["bonus_kk"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_summonerbonussettings_enabled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bonus_kk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Надбавка за суммонеров, кк'),
        ),
        migrations.RunPython(backfill_bonus_kk, noop),
    ]
