# Generated by Django 6.1 on 2026-10-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_epicbossnotificationsettings_text_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicbossnotificationsettings',
            name='text_template',
            field=models.TextField(blank=True, default='🎮 Сегодня респ Эпик РБ\n\nБоссы:\n{bosses}\n\nОкно респа: ~24 часа.', help_text='Вместо {bosses} подставится список имён выбранных боссов.', verbose_name='Шаблон текста'),
        ),
    ]
